title: Open Wine Project
description: The Open Wine Project is a collection of data catalogs, ontologies, tools and more organized to support the Open Wine Intiative.
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Project Repository: https://github.com/OpenWineProject
