title: Open Wine Project
description: The Open Wine Project is a collection of data catalogs, ontologies, tools and more organized to support the Open Wine Intiative.
theme: just-the-docs

url: https://www.openwineproject.org

aux_links:
  Open Wine Initiative: https://openwineinitiative.org
  Project Repository: https://github.com/OpenWineProject
