title: Open Wine Project
description: The Open Wine Project is a collection of data catalogs, ontologies, tools and more organized to support the Open Wine Intiative.
theme: just-the-docs

url: https://openwineproject.org

ga_tracking: G-E3YR8PQHM6
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

aux_links:
  Open Wine Initiative: https://openwineinitiative.org
  Project Repository: https://github.com/OpenWineProject

plugins:
  - jekyll-leaflet